# Generated by Django 4.1.1 on 2022-10-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_siigo', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('iva', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('category', models.ManyToManyField(to='category.category')),
            ],
        ),
    ]
