# Generated by Django 4.1.1 on 2022-10-05 02:54

from django.db import migrations, models
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_siigo', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('iva', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('images', wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], use_json_field=None)),
            ],
        ),
    ]
