# Generated by Django 4.1.1 on 2022-10-03 23:00

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0076_modellogentry_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('categoria', wagtail.fields.StreamField([('categoria', wagtail.blocks.StructBlock([('titulo', wagtail.blocks.CharBlock()), ('imagen', wagtail.images.blocks.ImageChooserBlock()), ('pagina', wagtail.blocks.PageChooserBlock(label='page', required=False))]))], use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
