# Generated by Django 4.0.7 on 2022-08-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_porvenir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customporvenirimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
